import {
  Activity,
  AudioLines,
  BookOpen,
  Clock,
  Compass,
  Crown,
  Disc3,
  Drum,
  Ear,
  Eye,
  Flame,
  Gauge,
  Grid3x3,
  Guitar,
  Hand,
  Hash,
  Heart,
  Keyboard,
  Layers,
  Lightbulb,
  ListMusic,
  type LucideIcon,
  Map as MapIcon,
  Music,
  Music2,
  Music4,
  Piano,
  Repeat,
  Rocket,
  Route,
  Shuffle,
  SlidersHorizontal,
  Sparkles,
  Star,
  Target,
  Timer,
  Trophy,
  WandSparkles,
  Waves,
  Zap,
} from 'lucide-react'

/** Icons by name, so lesson content can stay plain data. */
export const ICONS = {
  activity: Activity,
  'audio-lines': AudioLines,
  book: BookOpen,
  clock: Clock,
  compass: Compass,
  crown: Crown,
  disc: Disc3,
  drum: Drum,
  ear: Ear,
  eye: Eye,
  flame: Flame,
  gauge: Gauge,
  grid: Grid3x3,
  guitar: Guitar,
  hand: Hand,
  hash: Hash,
  heart: Heart,
  keyboard: Keyboard,
  layers: Layers,
  lightbulb: Lightbulb,
  'list-music': ListMusic,
  map: MapIcon,
  music: Music,
  music2: Music2,
  music4: Music4,
  piano: Piano,
  repeat: Repeat,
  rocket: Rocket,
  route: Route,
  shuffle: Shuffle,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  wand: WandSparkles,
  waves: Waves,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS
